### ISSUE TITLE
Reporter should maybe reset its statistics after RunAllTests()

### ISSUE THREAD

**Issue by lanurmi** [neacsum/utpp#13]
If you call ` UnitTest::RunAllTests();` twice (for whatever reason), unlike with UnitTest++, you will get cumulative statistics for the number of tests and run time.

Like this:

```
Success: 1200 tests passed.
Run time: 8.21
...
Success: 2400 tests passed.
Run time: 15.72
```

On one hand this makes sense, but on another hand it is misleading.

This can be worked around by supplying one's own reporter that is not reused for the second run:
```
{ UnitTest::ReporterStream rpt;
UnitTest::RunAllTests(rpt); }
```

Still, I think the statistics should be reset after each `RunAllTests()` call by default.

(Running tests twice may not be terribly common; in my use case we do it to run the tests with two different locales.)

**Comment by neacsum** [comment]
I've added a function `Reporter::Clear()` that is called by `RunAllTests()`. It can also be called by users if they need to reset statistics for whatever reason.

**Comment by lanurmi** [comment]
Thanks again for the quick fix!

Let me suggest this change to avoid warnings by some compilers:

```
--- a/include/utpp/reporter_xml.h
+++ b/include/utpp/reporter_xml.h
@@ -25,7 +25,7 @@ public:
   explicit ReporterXml (std::ostream& ostream = std::cout);

   int Summary () override;
-  void Clear ();
+  void Clear () override;

 protected:
   void BeginTest (const ReporterDeferred::TestResult& result);

```

**Comment by neacsum** [comment]
Thanks, good catch! Will do.
