### ISSUE TITLE
Arguments of CHECK_THROW are in reversed order (compared to UnitTest++)

### ISSUE THREAD

**Issue by lanurmi** [neacsum/utpp#2]
While in UnitTest++ the order of `CHECK_THROW` arguments is [(expression, exceptiontype)](https://github.com/unittest-cpp/unittest-cpp/blob/10e50ad70c696002b1d5bbefd0ea04b3ea92a03b/UnitTest%2B%2B/CheckMacros.h#L182), in UTPP the arguments are [reversed](https://github.com/neacsum/utpp/blob/master/include/utpp/checks.h#L317). This is obviously API-incompatible with UnitTest++.

**Comment by neacsum** [comment]
Thanks for pointing that out. I will revise it or you can do a pull request. On Mar 11, 2024, at 09:02, Lauri Nurmi ***@***.***> wrote:﻿
While in UnitTest++ the order of CHECK_THROW arguments is (expression, exceptiontype), in UTPP the arguments are reversed. This is obviously API-incompatible with UnitTest++.
