### ISSUE TITLE
Fixture name ignored in fixture class naming

### ISSUE THREAD

**Issue by lanurmi** [neacsum/utpp#9]
Here's another subtle API incompatibility. Consider the following code, which is fine with UnitTest++:

```c++
class C {
public:
    int get() { return 1; }
};

class D : public C {
};

TEST_FIXTURE(C, getter) {
    C c;
    CHECK_EQUAL(1, c.get());
}

TEST_FIXTURE(D, getter) {
    D d;
    CHECK_EQUAL(1, d.get());
}
```

This does not compile with UTPP, as UTPP expands e.g. `TEST_FIXTURE(C, getter)` just to `class Testgetter ...`, which is equal to the expansion of `TEXT_FIXTURE(D, getter)`. The compiler sees that as a redefinition of the class.

The name of the fixture should be part of the class name, something like this:
```diff
 #define TEST_FIXTURE(Fixture, Name)                                           \
-  class Test##Name : public Fixture, public UnitTest::Test                    \
+  class Fixture##Name##Helper : public Fixture, public UnitTest::Test         \
   {                                                                           \
```

`Fixture##Name##Helper` matches what UnitTest++ uses, at least the version that I have.

**Comment by neacsum** [comment]
Yes, it is a slight incompatibility but I would argue that you can easily go around it by changing the test name (for instance `C_getter` and `D_getter`). Also, having unique test names, makes it easier to interpret the results.

That being said, if you feel that it is important, I will go ahead and fix it.
